function [integrated_tracers]=integrate_tracers(tr)
options=odeset('AbsTol',1e-12,'RelTol',1e-12);
for i=1:tr.n_tracers
	fprintf('Integrating tracer n. %i of %i\n',i,tr.n_tracers)
	[t,Y]=ode45(...
		@f_ell,...
		[tr.t0 tr.t0+tr.T],...
		[tr.x(i); tr.y(i); tr.vx(i); tr.vy(i)],...
		options,...
		tr.mu,...
		tr.ecc);
	traj{i,1}=Y;
	traj{i,2}=t;
	% Add energy column
	%keyboard
	traj{i,1}(:,5)=0.5*(Y(:,3).^2+Y(:,4).^2)-(Omega(Y(:,1),Y(:,2),tr.mu)./(1+tr.ecc*cos(t)));
end
integrated_tracers=traj;